### ISSUE TITLE
Voice Recording

### ISSUE THREAD

**Issue by nandinib1999** [shankhanil007/DotSlash-4.0-EduHelp#2]
AFAIK, if you move your application to a web-based setup, you will not be able to record audio on the deployment server. Refer https://stackoverflow.com/questions/62365299/deploy-django-app-using-pyaudio-library-to-heroku.

You will have to implement client-side recording of audio using JavaScript. I would like to work on this. Let me know if you think this is a valid issue.

I am a GSSOC'21 participant.

**Comment by shankhanil007** [comment]
Thanks a lot for showing interest in our project.  We are currently in the process of creating issues for the participants. We will surely review your request and let you know accordingly.

**Comment by nandinib1999** [comment]
Thanks a lot!

**Comment by fomalhauting** [comment]
@shankhanil007 When will the issues be available?

**Comment by shankhanil007** [comment]
You can expect them to be released latest by this Friday or Saturday.

**Comment by GrayFlash** [comment]
@itsIapetus we have released a issue and are in discussion about setting up other beginner-friendly issues which will help you setup a local environment for development as well as give give you a grasp of our project.
Visit here, our official repo for GSSoC 2021 and get started... 
https://github.com/CrewMates-Open-Source/EduHelp.git
